"""add_proposed_award

Revision ID: 1b8525245472
Revises: 91f1732f0e4b
Create Date: 2026-05-21 15:48:35.662047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8525245472'
down_revision: Union[str, Sequence[str], None] = '91f1732f0e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('proposed_award', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'proposed_award')
    # ### end Alembic commands ###
