"""initial schema: users, cycles, employees, approvals, audit, budgets

Revision ID: 63398eefd33b
Revises: 
Create Date: 2026-05-19 23:22:16.805639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63398eefd33b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('review_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fy_label', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('letter_date', sa.Date(), nullable=False),
    sa.Column('consultation_deadline', sa.Date(), nullable=True),
    sa.Column('cpi_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('super_old', sa.String(length=10), nullable=True),
    sa.Column('super_new', sa.String(length=10), nullable=True),
    sa.Column('signatory_name', sa.String(length=120), nullable=True),
    sa.Column('signatory_title', sa.String(length=160), nullable=True),
    sa.Column('signatory_company', sa.String(length=120), nullable=True),
    sa.Column('hr_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('wage_model_filename', sa.String(length=255), nullable=True),
    sa.Column('wage_model_path', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fy_label')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_notes', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'site', name='uq_approval_cycle_site')
    )
    op.create_index(op.f('ix_approvals_cycle_id'), 'approvals', ['cycle_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('max_increase_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_total_payroll', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'site', name='uq_budget_cycle_site')
    )
    op.create_index(op.f('ix_budgets_cycle_id'), 'budgets', ['cycle_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('emp_num', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('hours_per_week', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fy25_award', sa.String(length=60), nullable=True),
    sa.Column('current_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fy26_award', sa.String(length=60), nullable=True),
    sa.Column('pp_level', sa.String(length=120), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=True),
    sa.Column('change_input', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('proposed_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('letter_type', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_departed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'emp_num', name='uq_employee_cycle_empnum')
    )
    op.create_index('ix_employee_cycle_site', 'employees', ['cycle_id', 'site'], unique=False)
    op.create_index(op.f('ix_employees_cycle_id'), 'employees', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_employees_site'), 'employees', ['site'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_site'), table_name='employees')
    op.drop_index(op.f('ix_employees_cycle_id'), table_name='employees')
    op.drop_index('ix_employee_cycle_site', table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_budgets_cycle_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_approvals_cycle_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('review_cycles')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
