"""add_historical_compliance_columns

Revision ID: 91f1732f0e4b
Revises: 962044c71bb9
Create Date: 2026-05-21 15:38:16.282224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f1732f0e4b'
down_revision: Union[str, Sequence[str], None] = '962044c71bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hist_award_level_changed', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('hist_rate_changed', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('hist_above_award_rate', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('hist_above_pp_rate', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('hist_above_pp_max', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'hist_above_pp_max')
    op.drop_column('employees', 'hist_above_pp_rate')
    op.drop_column('employees', 'hist_above_award_rate')
    op.drop_column('employees', 'hist_rate_changed')
    op.drop_column('employees', 'hist_award_level_changed')
    # ### end Alembic commands ###
