"""add_compliance_suppressions

Revision ID: 962044c71bb9
Revises: a59e846b9223
Create Date: 2026-05-21 14:54:25.771600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962044c71bb9'
down_revision: Union[str, Sequence[str], None] = 'a59e846b9223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_suppressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('check_label', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('suppressed_by_id', sa.Integer(), nullable=False),
    sa.Column('suppressed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undone_by_id', sa.Integer(), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suppressed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['undone_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'check_label', 'is_active', name='uq_suppression_employee_label_active')
    )
    op.create_index('ix_suppression_employee_id', 'compliance_suppressions', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suppression_employee_id', table_name='compliance_suppressions')
    op.drop_table('compliance_suppressions')
    # ### end Alembic commands ###
